### ISSUE TITLE
The music stops after 30 seconds

### ISSUE THREAD

**Issue by Sade112** [Mhmd-Akh/radio-harmony#1]
**Describe the bug**
The bot joins the channel and start playing music, all normal, but after a few seconds the music just stops, i restarted using the restart channel but after a few second stops again and again

**Comment by Mhmd-Akh** [comment]
> **Describe the bug** The bot joins the channel and start playing music, all normal, but after a few seconds the music just stops, i restarted using the restart channel but after a few second stops again and again

What is the link you posted playing music?

**Comment by Mhmd-Akh** [comment]
> **Describe the bug** The bot joins the channel and start playing music, all normal, but after a few seconds the music just stops, i restarted using the restart channel but after a few second stops again and again

What is the link you posted playing music?

**Comment by Mhmd-Akh** [comment]
What is the link you posted playing music?

**Comment by Mhmd-Akh** [comment]
> **Describe the bug** The bot joins the channel and start playing music, all normal, but after a few seconds the music just stops, i restarted using the restart channel but after a few second stops again and again

What is the link you posted playing music?

**Comment by Sade112** [comment]
The bot stops after 50 sec, no matter what link i use, i tested on YouTube links, radio links, etc and it stops playing, the bot dont write on anny channel aswell.

**Comment by Sade112** [comment]
Add me on dicord please Sade_112#5711

**Comment by Mhmd-Akh** [comment]
> Add me on dicord please Sade_112#5711

ok
